import type { NextPage } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { PageWrapper, Box, Searchbar, QueryComponent } from 'components';
import { useEffect } from 'react';
import { useAppDispatch, AppDispatch, useAppSelector, RootState } from 'redux/rootStore';
import { queryResults } from 'redux/slices/querySlice';

// import { useEffect } from 'react';
// import { axiosHanlder } from 'axios_handler/handler';
// import { useEffect } from 'react';

const Detail: NextPage = () => {
    const router = useRouter();
    const { queryResults } = useAppSelector((state: RootState) => state.querySlice);

    // useEffect(() => {}, [router]);
    return (
        <PageWrapper>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <>{console.log(router)}</>
            <>{console.log(queryResults)}</>
            {/* <QueryComponent />
            <Box className="flex justify-center relative top-[30%]">
                <Searchbar />
            </Box> */}
            <p>{/* <>{console.log(countRef.current)}</> */}</p>
        </PageWrapper>
    );
};

export default Detail;
