import type { NextPage } from 'next';
import Head from 'next/head';
import {
    SearchResultBox,
    Box,
    Logo,
    QueryComponent,
    PageInnerWrapper,
    PageWrapper,
    Searchbar,
    ShowQueryTime,
    LoadMoreDocs,
} from 'components';

const Detail: NextPage = () => {
    return (
        <PageWrapper>
            <PageInnerWrapper>
                <Head>
                    <title>Create Next App</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <QueryComponent />
                <Box className="py-3">
                    <Logo />
                    <Searchbar />
                    <ShowQueryTime />
                </Box>
                <SearchResultBox className="grid gap-8 px-5" />
                <LoadMoreDocs />
            </PageInnerWrapper>
        </PageWrapper>
    );
};

export default Detail;
