import type { NextPage } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { PageWrapper, Box, Searchbar, QueryComponent } from 'components';

// import { useEffect } from 'react';
// import { axiosHanlder } from 'axios_handler/handler';
// import { useEffect } from 'react';

const Detail: NextPage = () => {
    const router = useRouter();
    return (
        <PageWrapper>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {/* <QueryComponent />
            <Box className="flex justify-center relative top-[30%]">
                <Searchbar />
            </Box> */}
            <p>{/* <>{console.log(countRef.current)}</> */}</p>
        </PageWrapper>
    );
};

export default Detail;
