import type { NextPage } from 'next';
import Head from 'next/head';
import { PageWrapper, PageInnerWrapper, Box, Searchbar, QueryComponent, Logo } from 'components';
import Image from 'next/image';
import logo from 'public/logoipsum1.svg';
import { useEffect } from 'react';
import { axiosHandler } from 'axios_handler/handler';
// import { useEffect } from 'react';

const Home: NextPage = () => {
    return (
        <PageWrapper>
            <PageInnerWrapper>
                <Head>
                    <title>Create Next App</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <QueryComponent />
                <Box className="mt-3 md:mt-[10%] ">
                    <Logo />
                    <Searchbar />
                </Box>
            </PageInnerWrapper>
        </PageWrapper>
    );
};

export default Home;
